from typing import Dict, Any
from core.interfaces import SubconsciousUnit, SwarmSignal
import time

class ReflectionSwarm(SubconsciousUnit):
    """
    The Voice of Experience (Infinite Why).
    
    Reads the 'reflection' from the AGI generated by the InfiniteWhyEngine.
    Votes based on causal consistency and historical success of similar patterns.
    """

    def __init__(self, name: str = "Reflection_Swarm"):
        super().__init__(name)

    async def process(self, context: Dict[str, Any]) -> SwarmSignal:
        tick = context.get('tick', {})
        reflection = tick.get('agi_reflection', {}) # Injected by main loop
        
        if not reflection:
            return None
            
        # Analysis logic
        # If the "Why" engine says we succeeded in similar past events, we vote YES.
        
        similar_success_rate = reflection.get('similar_success_rate', 0.5)
        causal_strength = reflection.get('causal_confidence', 0.0)
        
        signal = "WAIT"
        confidence = 0.0
        
        if similar_success_rate > 0.6:
            # History says Yes
            # Determine direction from context or assume trend continuation?
            # Reflection needs to provide "suggested_action"
            suggested = reflection.get('suggested_action', 'WAIT')
            
            if suggested in ["BUY", "SELL"]:
                signal = suggested
                confidence = similar_success_rate * 100.0
        
        if signal == "WAIT":
             return None
             
        return SwarmSignal(
            signal_type=signal,
            confidence=confidence,
            source=self.name,
            meta_data=reflection,
            timestamp=time.time()
        )
